version: '3.8'

services:
  frontend:
    build:
      context: .
      target: development
    container_name: vrgestorpdvui-dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.angular/cache
